package constant

var NaverAddr = map[string]string{
	"아이텐":       "https://smartstore.naver.com/i-10",
	"기기레코즈":     "https://smartstore.naver.com/gigirecords",
	"바이닐코리아":    "https://smartstore.naver.com/vinylkor",
	"마이페이보릿스토어": "https://smartstore.naver.com/cinemastore",
	"하이닐":       "https://smartstore.naver.com/hinyl",
	"테리픽잼":      "https://smartstore.naver.com/terrific_jam",
	"레코드스톡":     "https://smartstore.naver.com/recordstock",
	"라보앤드":      "https://smartstore.naver.com/lavoand",
	"마뮤":        "https://smartstore.naver.com/mamustore",
	"판다바이닐":     "https://smartstore.naver.com/pandavinyl",
	"뮤직랜드":      "https://smartstore.naver.com/musicland",
	"구해줘굿즈":     "https://smartstore.naver.com/getgoods",
	"아메리칸오리진":   "https://smartstore.naver.com/watsons",
	"모카홀릭":      "https://smartstore.naver.com/byeolne",
	"쳇베이커리":     "https://smartstore.naver.com/chetbakery",
	"바이어티":      "https://smartstore.naver.com/buyerty",
	"라운드뮤직":     "https://smartstore.naver.com/sun_musicstore2019",
	"인펙션스 레코드":  "https://smartstore.naver.com/infectionsrecord",
	"비트볼 뮤직":    "https://smartstore.naver.com/beatball",
	"서울 바이닐":    "https://smartstore.naver.com/seoulvinyl",
	"더 슬로우 샵":   "https://smartstore.naver.com/theslowshop",
	"서울 레코드":    "https://smartstore.naver.com/seoulrecord",
	"사운드룩":      "https://smartstore.naver.com/soundlook",
	"드림 레코드":    "https://smartstore.naver.com/dreamrec",
	"바이닐 앤 바이브": "https://smartstore.naver.com/vinylnvibe",
	"아이러브뮤직":    "https://smartstore.naver.com/ilovemusic_kr",
	"슬로우바이닐":    "https://smartstore.naver.com/slowvinyl",
	"월간바이닐":     "https://smartstore.naver.com/allthatvinyl",
	"뮤니버스24":    "https://smartstore.naver.com/muniverse24",
	"스피츠레코드":    "https://smartstore.naver.com/spitzrecords",
	"미드나잇스낵":    "https://smartstore.naver.com/midnightsnack",
	"신나라레코드":    "https://smartstore.naver.com/synnara-nshop",
}
